### PR TITLE
Update ui.html

### PR DESCRIPTION
**Pull request by Zan1456**
image
image
image
image

### CODE REVIEW

**Comment by TheFantomas** [comment]
Please make a fork of repository and only do one pr please :D

**Comment by Zan1456** [comment]
> Please make a fork of repository and only do one pr please :D

Sorry, I just don't know how to use github in this area yet.

**Comment by CsokiHUN** [comment]
Thank you for the PR. But as @TheFantomas wrote, please also open a new PR. If you can't do it, I will do it manually.

**Comment by Zan1456** [comment]
Please do it and next time I'll look into how to use it.
https://github.com/Zan1456/esx_dmvschool

**Comment by TheFantomas** [comment]
Just open you repository https://github.com/Zan1456/esx_dmvschool and click on the blue text
image

then on Create pull request
image

and create pr 
image

**Comment by TheFantomas** [comment]
If you still don't understand, we'll do it for you

**Comment by CsokiHUN** [comment]
btw, could we ignore the German javascript code in the html/script.js file I see

**Pull request closed without merging**
