### PR TITLE
Update ui_en.html

### PR DESCRIPTION
**Pull request by kamuzaki**
On the English (ui_en.html) questionnaire has to take the "questions_en.js"

### CODE REVIEW

**Comment by HumanTree92** [comment]
You know this is pointless right. If you use English you simply rename ui.html to ui_fr.html and then change ui_en.html to ui.html & you do the same thing to the questions.

**Comment by kamuzaki** [comment]
You know this is pointless right..?
It is just a change in the code so everyone onwards download the right file and not come back and pull requests.. 💁

**Comment by HumanTree92** [comment]
> 
> 
> You know this is pointless right..?
> It is just a change in the code so everyone onwards download the right file and not come back and pull requests.. Or search in the Internet how to solve this. 👏

https://github.com/ESX-Org/esx_dmvschool/pull/46

And the reason why i say pointless is due to esx_ scripts made by ESX-Org are no longer being maintained.

**Comment by LazarusOfTheFallen** [comment]
@HumanTree92 I will still approve PRs if they are significant.

**Pull request closed without merging**
